config/routes.rb
Rails.application.routes.draw do
  get 'home/welcome'

  devise_for :users
  resources :users
  resources :stations
  resources :chains
  root "home#welcome"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chain.rb
class Chain < ApplicationRecord
end

app/models/station.rb
class Station < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #validates :name, presence: true
  validates :email, uniqueness: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception 

  
    before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :surname, :birthdate, :phonenumber, :email, :password) }
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :surname, :birthdate, :phonenumber, :email, :password, :current_password) }
        end

end

app/controllers/chains_controller.rb
class ChainsController < ApplicationController
  before_action :set_chain, only: [:show, :edit, :update, :destroy]

  # GET /chains
  # GET /chains.json
  def index
    @chains = Chain.all
  end

  # GET /chains/1
  # GET /chains/1.json
  def show
  end

  # GET /chains/new
  def new
    @chain = Chain.new
  end

  # GET /chains/1/edit
  def edit
  end

  # POST /chains
  # POST /chains.json
  def create
    @chain = Chain.new(chain_params)

    respond_to do |format|
      if @chain.save
        format.html { redirect_to @chain, notice: 'Chain was successfully created.' }
        format.json { render :show, status: :created, location: @chain }
      else
        format.html { render :new }
        format.json { render json: @chain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chains/1
  # PATCH/PUT /chains/1.json
  def update
    respond_to do |format|
      if @chain.update(chain_params)
        format.html { redirect_to @chain, notice: 'Chain was successfully updated.' }
        format.json { render :show, status: :ok, location: @chain }
      else
        format.html { render :edit }
        format.json { render json: @chain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chains/1
  # DELETE /chains/1.json
  def destroy
    @chain.destroy
    respond_to do |format|
      format.html { redirect_to chains_url, notice: 'Chain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chain
      @chain = Chain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chain_params
      params.require(:chain).permit(:status, :model, :securityLevel)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully mamma.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:lat, :long, :address, :number_chains, :station_number, :free_chains, :station_name, :lockers, :security)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :surname, :birthdate, :phonenumber, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chains_helper.rb
module ChainsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chains/_form.html.erb
<%= form_for(chain) do |f| %>
  <% if chain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chain.errors.count, "error") %> prohibited this chain from being saved:</h2>

      <ul>
      <% chain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :securityLevel %>
    <%= f.number_field :securityLevel %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chains/edit.html.erb
<h1>Editing Chain</h1>

<%= render 'form', chain: @chain %>

<%= link_to 'Show', @chain %> |
<%= link_to 'Back', chains_path %>

app/views/chains/index.html.erb
<p id="notice"><%= notice %></p>

 
<h1>Chains</h1>

<h1>CIAO VALE :-)</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Model</th>
      <th>Securitylevel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chains.each do |chain| %>
      <tr>
        <td><%= chain.status %></td>
        <td><%= chain.model %></td>
        <td><%= chain.securityLevel %></td>
        <td><%= link_to 'Show', chain %></td>
        <td><%= link_to 'Edit', edit_chain_path(chain) %></td>
        <td><%= link_to 'Destroy', chain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chain', new_chain_path %>

app/views/chains/new.html.erb
<h1>bo</h1>

<%= render 'form', chain: @chain %>

<%= link_to 'Back', chains_path %>

app/views/chains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @chain.status %>
</p>

<p>
  <strong>Model:</strong>
  <%= @chain.model %>
</p>

<p>
  <strong>Securitylevel:</strong>
  <%= @chain.securityLevel %>
</p>

<%= link_to 'Edit', edit_chain_path(@chain) %> |
<%= link_to 'Back', chains_path %>

app/views/home/welcome.html.1.erb
<p id="notice"><%= notice %></p>
    
<div class="jumbotron text-center">    
    <h1>Home#welcome</h1>
    <p>Find me in app/views/home/welcome.html.erb</p>
</div>
<% if !current_user.nil? %>
<%=    "benvenuto " + current_user.name + " " + current_user.surname + " (" + current_user.email + ")" %>
<p><%= link_to 'Modifica profilo', edit_user_registration_path, class: 'btn btn-primary' %></p>
<p><%= link_to 'Le stazioni di BeMISecure', stations_path, class: 'btn btn-primary' %></p>
<p><%= link_to 'Esci', destroy_user_session_path, :method => :delete, class: 'btn btn-primary' %></p>
<% else %>
<p><%= link_to 'Accedi', new_user_session_path, class: 'btn btn-primary' %></p>
<p><%= link_to 'Registrati', new_user_registration_path, class: 'btn btn-primary' %></p>
<% end %>

app/views/home/welcome.html.3.erb
<p id="notice"><%= notice %></p>

<div id="heroimage">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div id="content">
                    <h1>Page title</h1>
                    <p>Some Text</p>
                </div>
            </div>
        </div>
    </div>             
</div>

app/views/home/welcome.html.4.erb
<p id="notice"><%= notice %></p>

 <div class="container-fluid">
   <div class="row">
     <div class="col-sm-2 col-md-offset-2">
      <img src="<%= asset_path "ScambioIdee.jpg" %>" class="img-responsive img-circle">
      <h3>stazione 1</h3>
     </div>
     <div class="col-sm-2">
      <img src="<%= asset_path "ScambioIdee.jpg" %>" class="img-responsive img-circle">
      <h3>stazione 2</h3>
     </div>
     <div class="col-sm-2">
      <img src="<%= asset_path "ScambioIdee.jpg" %>" class="img-responsive img-circle">
      <h3>stazione 3</h3>
     </div>
      <div class="col-sm-2">
       <img src="<%= asset_path "ScambioIdee.jpg" %>" class="img-responsive img-circle">
       <h3>stazione 4</h3>
     </div>
   </div>
   <div class="row">
     <div class="col-sm-2 col-md-offset-2">
      <img src="<%= asset_path "ScambioIdee.jpg" %>" class="img-responsive img-circle">
      <h3>stazione 5</h3>
     </div>
     <div class="col-sm-2">
      <img src="<%= asset_path "ScambioIdee.jpg" %>" class="img-responsive img-circle">
      <h3>stazione 6</h3>
     </div>
     <div class="col-sm-2">
      <img src="<%= asset_path "ScambioIdee.jpg" %>" class="img-responsive img-circle">
      <h3>stazione 7</h3>
     </div>
      <div class="col-sm-2">
       <img src="<%= asset_path "ScambioIdee.jpg" %>" class="img-responsive img-circle">
       <h3>stazione 8</h3>
     </div>
   </div> 
 </div>

app/views/home/welcome.html.erb
<p id="notice"><%= notice %></p>
 <div class="hero__image">
    <img src="<%= asset_path "heroimage4.jpg" %>" alt="test" class="img-responsive">
    <div class="carousel-caption">
       <h1>Lorem ipsum set ardor</h1>
       <% if current_user.nil? %>       
        <p><%= link_to 'Registrati adesso', new_user_registration_path, class: 'btn btn-primary btn-lg' %></p>
       <% end %>
    </div>
 </div>
 <p></p>
 <div class="container-fluid">
   <div class="row">
     <div class="col-sm-4">
      <img src="<%= asset_path "ScambioIdee.jpg" %>" class="img-responsive img-circle">
      <h3>Come funziona</h3>
     </div>
     <div class="col-sm-4">
      <img src="<%= asset_path "ScambioIdee.jpg" %>" class="img-responsive img-circle">
      <h3>Chi siamo</h3>
     </div>
     <div class="col-sm-4">
      <img src="<%= asset_path "ScambioIdee.jpg" %>" class="img-responsive img-circle">
      <h3>Dove siamo</h3>
     </div>
   </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeMIsecure</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://unpkg.com/leaflet@1.0.2/dist/leaflet.css' %>
    <%= javascript_include_tag 'https://unpkg.com/leaflet@1.0.2/dist/leaflet.js' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">


  </head>

  <body>
  <nav class="navbar  navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="/">WebSiteName</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#" class=".btn-success">Page 1-1</a></li>
            <li><a href="#">Page 1-2</a></li>
            <li><a href="#">Page 1-3</a></li>
          </ul>
        </li>
        <li><a href="#">Page 2</a></li>
        <li><a href="#">Page 3</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user.nil? %>
          <li>
            <%= link_to  destroy_user_session_path, :method => :delete do %>
              <span class="glyphicon glyphicon-log-out"></span> Esci
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to new_user_session_path do %>
              <span class="glyphicon glyphicon-log-in"></span> Accedi
            <% end %>
          <li>
        <% end %>  
      </ul>
    </div>
</div>
</nav>
<%= yield %>
</body>
</html>

app/views/stations/_form.html.erb
<%= form_for(station) do |f| %>
  <% if station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "latitudine" %>
    <%= f.number_field :lat, :step => :any %>
  </div>

  <div class="field">
    <%= f.label "longitudine" %>
    <%= f.number_field :long,  :step => :any  %>
  </div>

  <div class="field">
    <%= f.label "indirizzo" %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :number_chains %>
    <%= f.number_field :number_chains %>
  </div>

  <div class="field">
    <%= f.label :station_number %>
    <%= f.number_field :station_number %>
  </div>

  <div class="field">
    <%= f.label :free_chains %>
    <%= f.number_field :free_chains %>
  </div>

  <div class="field">
    <%= f.label :station_name %>
    <%= f.text_field :station_name %>
  </div>

  <div class="field">
    <%= f.label :lockers %>
    <%= f.number_field :lockers %>
  </div>

  <div class="field">
    <%= f.label :security %>
    <%= f.number_field :security %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stations</h1>

 <div id="leafletMap"></div>

 <%= javascript_tag do %>
    var leafletMap= L.map('leafletMap').setView([45.463683, 9.190619], 9);
    L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
          maxZoom: 19,
          attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
        }).addTo(leafletMap);
    // icon 
    var greenIcon= L.icon({
    iconUrl: '<%= asset_path "bici_stencil.jpg" %>',
    iconSize: [30,36], // size1 of the icon
    iconAnchor: [8, 18], // point of the icon which will correspond to marker's location
    popupAnchor: [0, 0] // point from which the popup should open relative to the iconAnchor
        });

    var marker= new Array();
    <% @stations.each_with_index  do |station, contatore| %>
      marker[<%= contatore %>] = L.marker([<%= station.lat %>, <%= station.long %>], {icon: greenIcon}).addTo(leafletMap);
      marker[<%= contatore %>].bindPopup('<b> <%= station.station_name + " - " + station.address %> </b>');
    <%  end  %>
  <% end %>


<table>
  <thead>
    <tr>
      <th>Latitudine</th>
      <th>Longitudine</th>
      <th>Indirizzo</th>
      <th>Number chains</th>
      <th>Station number</th>
      <th>Free chains</th>
      <th>Station name</th>
      <th>Lockers</th>
      <th>Security</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.lat %></td>
        <td><%= station.long %></td>
        <td><%= station.address %></td>
        <td><%= station.number_chains %></td>
        <td><%= station.station_number %></td>
        <td><%= station.free_chains %></td>
        <td><%= station.station_name %></td>
        <td><%= station.lockers %></td>
        <td><%= station.security %></td>
        <td><%= link_to 'Show', station %></td>
        <td><%= link_to 'Edit', edit_station_path(station) %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitudine:</strong>
  <%= @station.lat %>
</p>

<p>
  <strong>Longitudine:</strong>
  <%= @station.long %>
</p>

<p>
  <strong>Longitudine:</strong>
  <%= @station.address %>
</p>

<p>
  <strong>Number chains:</strong>
  <%= @station.number_chains %>
</p>

<p>
  <strong>Station number:</strong>
  <%= @station.station_number %>
</p>

<p>
  <strong>Free chains:</strong>
  <%= @station.free_chains %>
</p>

<p>
  <strong>Station name:</strong>
  <%= @station.station_name %>
</p>

<p>
  <strong>Lockers:</strong>
  <%= @station.lockers %>
</p>

<p>
  <strong>Security:</strong>
  <%= @station.security %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :surname %>
    <%= f.text_field :surname %>
  </div>

  <div class="field">
    <%= f.label :birthdate %>
    <%= f.date_select :birthdate %>
  </div>

  <div class="field">
    <%= f.label :phonenumber %>
    <%= f.text_field :phonenumber %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Birthdate</th>
      <th>Phonenumber</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.surname %></td>
        <td><%= user.birthdate %></td>
        <td><%= user.phonenumber %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_registration_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @user.surname %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @user.birthdate %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @user.phonenumber %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>